version: "3"

services:
  backend:
    container_name: mann-eller-kvinne-backend
    image: "ghcr.io/lblend/mann-eller-kvinne:latest"
    ports:
      - "5000:5000"

  frontend:
    container_name: mann-eller-kvinne-frontend
    image: "ghcr.io/lblend/mann-eller-kvinne-frontend:latest"
    ports:
      - "3000:3000"
    depends_on:
      - backend
