# Default/template file for hyperparameters of rnn model

random_seed: 42

# Automatically infers
output_folder: "rnn"
log_folder: "rnn"

# Loading parameters
batch_size: 64
buffer_size: 10000

# Model paramaters
bidirectional: True

model_shapes:
    vocab_size: 1000
    embedding: 128
    lstm: 128
    dense: 64
    # Output layer is constant
    # output: 1


optimizer_type: "Adam"

optimizer_args:
    learning_rate: 1e-4

early_stopper:
    patience: 2
    verbose: 1

epochs: 50
